project_id = "jwsxbbtzcbxmchjxxokm"

[functions.analyseMessage]
verify_jwt = true

[functions.analytics-summary]
verify_jwt = true

[functions.analytics-distributions]
verify_jwt = true

[functions.analytics-environments]
verify_jwt = true
